name: Sync Project Board

on:
  push:
    branches:
      - main

jobs:
  sync-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run Project Sync Script
        env:
          GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: |
          gh repo edit --enable-projects=true
          npm install
          node scripts/sync-project.js
